services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: voucher_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./voucherSaas:/var/www/voucherSaas
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - voucher_net
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: voucher_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./voucherSaas:/var/www/voucherSaas
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - voucher_net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: voucher_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: voucher_saas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: voucher
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - voucher_net

  redis:
    image: redis:alpine
    container_name: voucher_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - voucher_net

networks:
  voucher_net:

volumes:
  db_data:
